version: "3"
services:
  account-observer:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./account-observer/Dockerfile
    volumes:
      - db_data:/usr/src/app
    env_file:
      - .env

  trader:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./trader/Dockerfile
    volumes:
      - db_data:/usr/src/app
    env_file:
      - .env
volumes:
  db_data:
